baseurl = "davicitoafc.github.io"
languageCode = "en-us"
title = "David C - Software Developer"
googleAnalytics = ""

[Author]
  name = "David Cisneros"
  email = "youremail@domain.com"
  facebook = "username"
  github = "davicitoafc"
  instagram = "username"
  twitter = "daveedcis"
  linkedin = "https://www.linkedin.com/in/davidcis/"
  stackoverflow = ""
  soundcloud = ""
  wikipedia = ""
