baseurl = "http://davidcis/"
languageCode = "en-us"
title = "David C - Software Developer"
googleAnalytics = ""

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  github = ""
  instagram = "username"
  twitter = "username"
  linkedin = ""
  stackoverflow = ""
  soundcloud = ""
  wikipedia = ""
